export default {
  FONT_MTD : 'MTD-Magnies',
  FONT_OSWALD_BOLD : 'Oswald-Bold',
  FONT_OSWALD_EXTRALIGHT : 'Oswald-ExtraLight',
  FONT_OSWALD_LIGHT : 'Oswald-Light',
  FONT_OSWALD_MEDIUM : 'Oswald-Medium',
  FONT_OSWALD_REGULAR : 'Oswald-Regular',
  FONT_OSWALD_SEMIBOLD : 'Oswald-SemiBold',
  FONT_OSWALD_VARIABLEFONT_WGHT : 'Oswald-VariableFont_wght',

  FONT_SARABUN_BOLD : 'Sarabun-Bold',
  FONT_SARABUN_BOLDITALIC : 'Sarabun-BoldItalic',
  FONT_SARABUN_EXTRABOLD : 'Sarabun-ExtraBold',
  FONT_SARABUN_EXTRABOLDITALIC : 'Sarabun-ExtraBoldItalic',
  FONT_SARABUN_EXTRALIGHT : 'Sarabun-ExtraLight',
  FONT_SARABUN_EXTRALIGHTITALIC : 'Sarabun-ExtraLightItalic',
  FONT_SARABUN_ITALIC : 'Sarabun-Italic',
  FONT_SARABUN_LIGHT : 'Sarabun-Light',
  FONT_SARABUN_LIGHTITALIC : 'Sarabun-LightItalic',
  FONT_SARABUN_MEDIUM : 'Sarabun-Medium',
  FONT_SARABUN_MEDIUMITALIC : 'Sarabun-MediumItalic',
  FONT_SARABUN_REGULAR : 'Sarabun-Regular',
  FONT_SARABUN_SEMIBOLD : 'Sarabun-SemiBold',
  FONT_SARABUN_SEMIBOLDITALIC : 'Sarabun-SemiBoldItalic',
  FONT_SARABUN_THIN : 'Sarabun-Thin',
  FONT_SARABUN_THINITALIC : 'Sarabun-ThinItalic',
};
